
# Microservice Application Port Settings
spring.application.name=product-service
server.port=8081

# MySQL Database Routing Connection via Docker
spring.datasource.url=jdbc:mysql://localhost:3307/product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Structural Database Mapping Engine Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Java 21 Performance Tuning Optimization: Virtual Threads Implementation
spring.threads.virtual.enabled=true