
# Microservice Service Networking Config
spring.application.name=order-service
server.port=8082

# Oracle DB Container Routing Connection (Pluggable Database Scheme)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=order_user
spring.datasource.password=orderpassword
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate SQL Generation Engine Dialect for Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Java 21 High-Performance Virtual Thread Core Optimization
spring.threads.virtual.enabled=true
